### ISSUE TITLE
Laravel 11 compatibility

### ISSUE THREAD

**Issue by harmenjanssen** [michaeldzjap/Two-Factor-Authentication#12]
I'm looking into upgrading an application using your package to Laravel 11. This package is not compatible, according to its `composer.json`. 

Would you be willing to update the version constraint in this package to provide Laravel 11 compatibility?
Or if you think there are compatibility issues, would you be willing to accept a Pull Request that fixes these issues?

**Comment by michaeldzjap** [comment]
Yeah, I haven't got around to doing that. Personally, I don't need this package anymore, so it has been a low priority for me. But I'd be willing to update the version constraint if you want, sure. If [Laravel UI](https://github.com/laravel/ui) works with _Laravel_ 11, then so should this package in theory.

I will have a look at it this weekend. If its literally just bumping the version constraints then I will make a new release right away. If more work is needed it could take a little while longer I'm afraid.

**Comment by harmenjanssen** [comment]
Wow, that would be great! Looking forward to hearing from you. 
Thanks for the swift reply. 🙂

**Comment by michaeldzjap** [comment]
Added support for _Laravel_ 11 in v3.4.0. Hope it works for you.

**Comment by harmenjanssen** [comment]
Thanks you so much!
