### ISSUE TITLE
Support for Laravel 7? 

### ISSUE THREAD

**Issue by codepotato** [michaeldzjap/Two-Factor-Authentication#6]
Thanks for this great package, but I've just tried installing on Laravel 7 and it's not compatible. Do you have any plans to update this or should I send in a pull request with the update?

**Comment by michaeldzjap** [comment]
Yes absolutely. I just haven't got around to doing it yet. I'm planning to do it soonish (somewhere in the next 2 weeks). You're more than welcome to submit a PR for it if you want, although I can't guarantee I will be able to release a new version right away.

**Comment by codepotato** [comment]
Already on it :) @michaeldzjap

**Comment by codepotato** [comment]
Working on it over here at the moment : https://github.com/CodepotatoLtd/laravel-two-factor-authentication

**Comment by michaeldzjap** [comment]
@codepotato I went ahead and published a new version with support for _Laravel_ 7.*. I tested it with [this](https://github.com/michaeldzjap/laravel-two-factor-authentication-example) and it seems to work fine, so should be good to use for you. If not, let me know.

**Comment by codepotato** [comment]
Winner thanks Michael. Turns out just needed to update the illuminate/support dependencies. Dead simple. Thanks again! Do you have a donate link or anything to contribute towards?

**Comment by michaeldzjap** [comment]
@codepotato Sure, no problem. Thanks for the offer, but no need to donate.

**Comment by codepotato** [comment]
@michaeldzjap I have another question ref this package that I wondered if I could run past you. I'll open another issue if that's okay.
